services:
  mysql:
    image: mysql:8.0
    container_name: PLOCO_database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: react_ploclo
      MYSQL_USER: test
      MYSQL_PASSWORD: 123456
      # เพิ่มตัวแปร charset และ collation
      MYSQL_INITDB_SKIP_TZINFO: 1
      MYSQL_CHARSET: utf8mb4
      MYSQL_COLLATION: utf8mb4_unicode_ci
    ports:
      - "3308:3306"
    volumes:
      - ./migration/init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql-data:/var/lib/mysql
      - ./my.cnf:/etc/mysql/my.cnf  # Mount ไฟล์ my.cnf ที่กำหนดค่า character set
    command:
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --explicit-defaults-for-timestamp  # เพื่อหลีกเลี่ยงปัญหาการใช้ timestamp

volumes:
  mysql-data:
